language: node_js
node_js:
  - "10"

script:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then npm run build; fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: dist
  target-branch: master
  on:
    branch: develop